#!/usr/bin/python

import sys


try:
    import nbyum
except ImportError:
    # We're probably running in a development environment
    import os

    if os.path.exists("./src/nbyum"):
        sys.path.append(os.path.join(os.path.dirname(sys.argv[0]), "src"))
        import nbyum


if __name__ == "__main__":
    parser = nbyum.utils.get_parser()
    args = parser.parse_args()

    yummy = nbyum.NBYumCli(args)
    exit_code = yummy.run()

    sys.exit(exit_code)
